version: '3'
services: 
  photo-gallery:
    container_name: photo-gallery
    image: photo-gallery
    restart: always
    build: .
    ports:
      - '80:1234'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
